/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.3.3.7                                               */
/*  Date (dd.mm.yyyy):  6. 3.2018   Time (hh:mm): 12:02                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_2 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_SYNERGY 25
#define DISPLAY_1_COLOR_TABLE_SIZE 26

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_BG 5
#define GX_PIXELMAP_ID_LOGO_ARROW 6
#define GX_PIXELMAP_ID_S7G2 7
#define GX_PIXELMAP_ID_SYNERGY 8
#define GX_PIXELMAP_ID_ARROW_LEFT 9
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 10

/* String Ids                                                                  */

#define GX_STRING_ID_HELLO_WORLD 1
#define GX_STRING_ID_CHECKBOX_TEXT 2
#define GX_STRING_ID_BUTTON_DISABLED 3
#define GX_STRING_ID_BUTTON_ENABLED 4
#define GX_STRING_ID_WINDOW1 5
#define GX_STRING_ID_WINDOW2 6
#define GX_STRING_ID_INSTRUCT_BUTTON 7
#define GX_STRING_ID_STR_ON 8
#define GX_STRING_ID_STR_OFF 9
#define GX_STRING_ID_LED1_ON 10
#define GX_STRING_ID_LED1_OFF 11
#define GX_STRING_ID_LED2_ON 12
#define GX_STRING_ID_LED2_OFF 13
#define GX_STRING_ID_LED3_ON 14
#define GX_STRING_ID_LED3_OFF 15
#define GX_STRING_ID_STRING_1 16
#define GX_STRING_ID_STRING_2 17
#define GX_STRING_ID_STRING_3 18
#define GX_STRING_ID_STRING_4 19
#define GX_STRING_ID_STRING_5 20
#define GX_STRING_ID_STRING_6 21
#define GX_STRING_ID_STRING_7 22
#define GX_STRING_ID_STRING_8 23
#define GX_STRING_ID_STRING_9 24
#define GX_STRING_ID_STRING_10 25
#define GX_STRING_ID_STRING_11 26
#define GX_STRING_ID_STRING_12 27
#define GX_STRING_ID_STRING_13 28
#define DISPLAY_1_STRING_TABLE_SIZE 29

#endif                                       /* sentry                         */
